#!/usr/bin/env ruby

require 'cgi'
require 'open-uri'

PROMPT = ">> "

class GoogleCalculator
  @@base = 'http://www.google.com/ig/calculator?q='
  @@matcher = /\{lhs: "([^"]*)",rhs: "([^"]*)",error: "([^"]*)",icc: (false|true)\}/

  def self.calculate( str, verbose=false )
    url = @@base + CGI.escape(str)
    response = open(url).read
    result = @@matcher.match( response )

    self.bug_out(response) if !result

    if result[3] != ''
      self.error_string( result[3] )
    else
      self.response_string( result[1], result[2], verbose )
    end
  end

  def self.parse_string( str )
    str.gsub!(/\\x[0-9a-f]{2}/) { |m| m[2..-1].hex.chr }
    str.gsub!("\240", ",")
    str.gsub!(/&#215;/, "*")
    str.gsub!(/\<sup\>[^\<]+\<\/sup\>/) { |m| "^" + m[5..-7] }
    str = CGI.unescapeHTML(str)
  end

  def self.error_string( error )
    err = self.parse_string(error)
    if err == "4"
      err = "4 -- no result found. Most likely no results"
    end

    "Error: #{err}"
  end

  def self.response_string( lhs, rhs, verbose )
    o = ""
    if verbose
      o += self.parse_string(lhs) + " = "
    end
    o += self.parse_string(rhs)
    o
  end

  def self.bug_out( response )
    $stderr.puts "Failed to parse response:"
    $stderr.puts "    #{response.inspect}"
    $stderr.puts "This is a bug."
    $stderr.puts "Please report this, including this output, at https://github.com/nickstenning/gc/issues."
    exit 1
  end
end

if $0 == __FILE__
  if $ARGV[0] == '-v'
    $ARGV.shift
    verbose = true
  end

  if $ARGV.length > 0
    puts GoogleCalculator.calculate( $ARGV.join(' '), verbose )
  else

    print PROMPT

    while str = $stdin.gets
      puts GoogleCalculator.calculate( str.strip, verbose )
      print PROMPT
    end

  end
end
